language: cpp

cache:
  - ccache: true

os:
  - windows

compiler:
  - msvc

env:
  - EA_CONFIG=Debug
  - EA_CONFIG=Release

before_script:
  - mkdir build_$EA_CONFIG
  - cd build_$EA_CONFIG
  - cmake .. -DEACOPY_BUILD_TESTS:BOOL=ON
  - cmake --build . --config $EA_CONFIG

script:
  - cd $TRAVIS_BUILD_DIR/build_$EA_CONFIG/test
  - ctest -C $EA_CONFIG -V || exit 1

